# Generated by Django 2.0.2 on 2018-03-02 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.IntegerField(default=0)),
                ('longitude', models.IntegerField(default=0)),
                ('closed', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=200)),
                ('fuel', models.CharField(max_length=200)),
                ('transmission', models.CharField(max_length=200)),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Availability')),
                ('dealerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Dealer')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Vehicle'),
        ),
    ]
